# old_sound_rabbit_mq:
#     connections:
#         default:
#             url: '%env(RABBITMQ_URL)%'
#    producers:
#        # use 'old_sound_rabbit_mq.task_producer' service to send data.
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#    consumers:
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#            queue_options:    { name: 'task'}
#            callback:         App\Consumer\TaskConsumer
old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        db_insert_producer:
            connection: default
            exchange_options: { name: 'db_insert_exchange', type: 'direct' }
    consumers:
        db_insert_consumer:
            connection: default
            exchange_options: { name: 'db_insert_exchange', type: 'direct' }
            queues:
                - { name: 'db_insert_queue', options: { durable: true } }
            callback: 'App\Service\DbInsertService::processMessage'